In [1]:
import numpy as np

In [12]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
np.zeros([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(4,20) #Es un intervalo abierto [4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [28]:
arreglo_pares = np.arange(0,20,2)

In [23]:
np.arange(-12,0,0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5])

In [25]:
print(arreglo_pares.size)
print(len(arreglo_pares))

10
10


In [27]:
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

(2, 3, 4)


In [29]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [30]:
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [33]:
arreglo_24 = np.arange(24)

In [35]:
arreglo_24.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [36]:
arreglo_24.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [37]:
arreglo_24.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [38]:
arreglo_24.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [39]:
arreglo_24.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [40]:
arreglo_24.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
arreglo_24.reshape(2,2,6)

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [42]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [43]:
a + b

array([15, 15, 15])

In [44]:
a - b

array([5, 5, 5])

In [45]:
a * b

array([50, 50, 50])

In [46]:
a / b

array([2., 2., 2.])

In [64]:
arreglo_3d_one = np.arange(18,36,1).reshape(2,3,3)
arreglo_3d_two = np.arange(-9,9,1).reshape(2,3,3)

In [56]:
print(arreglo_3d)

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]]]


In [53]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
arreglo_3d_one + arreglo_3d_two

array([[[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]],

       [[27, 29, 31],
        [33, 35, 37],
        [39, 41, 43]]])

In [66]:
arreglo_3d_one - arreglo_3d_two

array([[[27, 27, 27],
        [27, 27, 27],
        [27, 27, 27]],

       [[27, 27, 27],
        [27, 27, 27],
        [27, 27, 27]]])

In [67]:
arreglo_3d_one * arreglo_3d_two

array([[[-162, -152, -140],
        [-126, -110,  -92],
        [ -72,  -50,  -26]],

       [[   0,   28,   58],
        [  90,  124,  160],
        [ 198,  238,  280]]])

In [69]:
arreglo_3d_two / arreglo_3d_one

array([[[-0.5       , -0.42105263, -0.35      ],
        [-0.28571429, -0.22727273, -0.17391304],
        [-0.125     , -0.08      , -0.03846154]],

       [[ 0.        ,  0.03571429,  0.06896552],
        [ 0.1       ,  0.12903226,  0.15625   ],
        [ 0.18181818,  0.20588235,  0.22857143]]])

In [70]:
arreglo_3d_two % arreglo_3d_one

array([[[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [71]:
arreglo_3d_one * 10

array([[[180, 190, 200],
        [210, 220, 230],
        [240, 250, 260]],

       [[270, 280, 290],
        [300, 310, 320],
        [330, 340, 350]]])

In [72]:
arreglo_3d_one + 7

array([[[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33]],

       [[34, 35, 36],
        [37, 38, 39],
        [40, 41, 42]]])

In [73]:
arreglo_3d_one - 7

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [74]:
arreglo_3d_one / 3

array([[[ 6.        ,  6.33333333,  6.66666667],
        [ 7.        ,  7.33333333,  7.66666667],
        [ 8.        ,  8.33333333,  8.66666667]],

       [[ 9.        ,  9.33333333,  9.66666667],
        [10.        , 10.33333333, 10.66666667],
        [11.        , 11.33333333, 11.66666667]]])

In [75]:
arreglo_3d_one % 4

array([[[2, 3, 0],
        [1, 2, 3],
        [0, 1, 2]],

       [[3, 0, 1],
        [2, 3, 0],
        [1, 2, 3]]])

In [76]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [77]:
arreglo_muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [125]:
resp = (arreglo_muestra > 5) & (arreglo_muestra < 12) & (arreglo_muestra%2==0)

In [126]:
arreglo_muestra[resp]

array([ 6,  8, 10])

In [91]:
resp = arreglo_muestra > 12  

In [128]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [129]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [130]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [131]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [132]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [133]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [134]:
arreglo_doce.sum()

66

In [135]:
arreglo_doce.min()

0

In [136]:
arreglo_doce.max()

11

In [138]:
arreglo_doce.reshape(3,2,2).sum()

66

In [145]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [146]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [144]:
arreglo_doce.reshape(6,2).sum(axis=1)

array([ 1,  5,  9, 13, 17, 21])