In [1]:
import numpy as np

In [3]:
arreglo_0_a_90_grados = np.array([0,30,45,60,90])
arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [4]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [5]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [6]:
np.sin(arreglo_0_a_90_grados)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [9]:
np.random.randint(10)

6